version: "3.9"

services:
  backend:
    build: .
    container_name: flask_contracts_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # PersistÃªncia do SQLite
    environment:
      FLASK_ENV: development
    restart: unless-stopped
